---
abstract: 'Simple wrapper around Linux L<btrfs> util.'
author:
  - 'Nikolay Martynov, C<< <kolya at cpan.org> >>'
  - 'Nikolay Martynov <kolya@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0
  IPC::System::Simple: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
  Try::Tiny: 0
  autodie: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Filesys-Btrfs
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  IPC::Cmd: 0
  Path::Class: 0
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
